# To find the app id, use the command: osascript -e 'id of app "SomeApp"'
# For example: osascript -e 'id of app "Visual Studio Code"'
---
- name: Allow for repeating key in apps
  community.general.osx_defaults:
    domain: "{{ item }}"
    key: ApplePressAndHoldEnabled
    type: bool
    value: false
    state: present
  loop:
    - com.jetbrains.intellij
    - com.jetbrains.goland
    - com.jetbrains.pycharm
    - com.jetbrains.WebStorm
    - com.microsoft.VSCode
