---
- name: Set dock icons size
  community.general.osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: float
    value: 42.0
    state: present
  notify: Reload dock

- name: Lock dock position
  community.general.osx_defaults:
    domain: com.apple.dock
    key: position-immutable
    type: bool
    value: true
    state: present
  notify: Reload dock

- name: Lock dock size
  community.general.osx_defaults:
    domain: com.apple.dock
    key: size-immutable
    type: bool
    value: true
    state: present
  notify: Reload dock

